package oauth

import (
	"time"
)

// TokenResponse is the authorization server response
type TokenResponse struct {
	Token        string            `json:"access_token"`
	RefreshToken string            `json:"refresh_token"`
	TokenType    string            `json:"token_type"` // bearer
	ExperesIn    int64             `json:"expires_in"` // secs
	Properties   map[string]string `json:"properties"`
}

// Token structure generated by the authorization server
type Token struct {
	Id           string            `json:"id_token"`
	CreationDate time.Time         `json:"date"`
	ExperesIn    time.Duration     `json:"expires_in"` // secs
	Credential   string            `json:"credential"`
	Scope        string            `json:"scope"`
	Claims       map[string]string `json:"claims"`
	TokenType    string            `json:"type"` // "U" for user, "C" for client
}

// RefreshToken structure included in the authorization server response
type RefreshToken struct {
	CreationDate   time.Time `json:"date"`
	TokenId        string    `json:"id_token"`
	RefreshTokenId string    `json:"id_refresh_token"`
	Credential     string    `json:"credential"`
	TokenType      string    `json:"type"` // "U" for user, "C" for client
	Scope          string    `json:"scope"`
}

type AuthorizeInfo struct {
	//授权类型，此值固定为“code”。
	ResponseType string `p:"response_type" v:"required"`
	//申请QQ登录成功后，分配给应用的appid。
	ClientId string `p:"client_id" v:"required"`
	//成功授权后的回调地址，必须是注册appid时填写的主域名下的地址，建议设置为网站首页或网站的用户中心。注意需要将url进行URLEncode。
	RedirectUri string `p:"redirect_uri" v:"required"`
	//client端的状态值。用于第三方应用防止CSRF攻击，成功授权后回调时会原样带回。请务必严格按照流程检查用户与state参数状态的绑定。
	State string `p:"state" v:"required"`
	//请求用户授权时向用户显示的可进行授权的列表。
	//可填写的值是API文档中列出的接口，以及一些动作型的授权（目前仅有：do_like），如果要填写多个接口名称，请用逗号隔开。
	//例如：scope=get_user_info,list_album,upload_pic,do_like
	//不传则默认请求对接口get_user_info进行授权。
	//建议控制授权项的数量，只传入必要的接口名称，因为授权项越多，用户越可能拒绝进行任何授权。
	Scope string `p:"scope"`
	//仅PC网站接入时使用。
	//用于展示的样式。不传则默认展示为PC下的样式。
	//如果传入“mobile”，则展示为mobile端下的样式。
	Display string `p:"display"`
}

type CancelAuthorizeInfo struct {
	//成功授权后的回调地址，必须是注册appid时填写的主域名下的地址，建议设置为网站首页或网站的用户中心。注意需要将url进行URLEncode。
	RedirectUri string `form:"redirect_uri" json:"redirect_uri" binding:"required"`
	//client端的状态值。用于第三方应用防止CSRF攻击，成功授权后回调时会原样带回。请务必严格按照流程检查用户与state参数状态的绑定。
	State string `form:"state" json:"state" binding:"required"`
}
